/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/FastCopy——XCopy 的 GUI 包装器设计': RouteRecordInfo<'/posts/FastCopy——XCopy 的 GUI 包装器设计', '/posts/FastCopy——XCopy 的 GUI 包装器设计', Record<never, never>, Record<never, never>>,
    '/posts/为 Chart 设计图标': RouteRecordInfo<'/posts/为 Chart 设计图标', '/posts/为 Chart 设计图标', Record<never, never>, Record<never, never>>,
    '/posts/为 NanaZip 设计图标': RouteRecordInfo<'/posts/为 NanaZip 设计图标', '/posts/为 NanaZip 设计图标', Record<never, never>, Record<never, never>>,
    '/posts/为 RX 文件资源管理器设计图标': RouteRecordInfo<'/posts/为 RX 文件资源管理器设计图标', '/posts/为 RX 文件资源管理器设计图标', Record<never, never>, Record<never, never>>,
    '/posts/为弹弹播放器设计图标': RouteRecordInfo<'/posts/为弹弹播放器设计图标', '/posts/为弹弹播放器设计图标', Record<never, never>, Record<never, never>>,
    '/posts/如何正确地将Unity导出的UWP工程的内容区域拓展到标题栏': RouteRecordInfo<'/posts/如何正确地将Unity导出的UWP工程的内容区域拓展到标题栏', '/posts/如何正确地将Unity导出的UWP工程的内容区域拓展到标题栏', Record<never, never>, Record<never, never>>,
    '/posts/重新设计 Crystal Disk Info': RouteRecordInfo<'/posts/重新设计 Crystal Disk Info', '/posts/重新设计 Crystal Disk Info', Record<never, never>, Record<never, never>>,
    '/posts/重新设计邮件': RouteRecordInfo<'/posts/重新设计邮件', '/posts/重新设计邮件', Record<never, never>, Record<never, never>>,
    '/posts/重新设计墨球': RouteRecordInfo<'/posts/重新设计墨球', '/posts/重新设计墨球', Record<never, never>, Record<never, never>>,
  }
}
